<a href="https://colab.research.google.com/github/Vedant950/MachineLearning/blob/main/Classification_Yelp(NLP).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [6]:
dataset = pd.read_csv('/content/yelp.csv')
X = dataset.iloc[:, 4].values
Y = dataset.iloc[:, 3].values

In [8]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
corpus = []
ps = PorterStemmer()
for i in range(0, 10000):
    review = re.sub('[^a-zA-Z]', ' ', X[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)

In [11]:
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression()
classifier1.fit(X_train, Y_train)

Y_pred1 = classifier1.predict(X_test)

print(confusion_matrix(Y_test, Y_pred1))
print(accuracy_score(Y_test, Y_pred1)*100)

[[ 72  39  18  11  10]
 [ 27  50  58  36   7]
 [ 14  29  94 112  35]
 [ 12  17  85 347 235]
 [  6   7  38 222 419]]
49.1


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 10)
classifier2.fit(X_train, Y_train)

Y_pred2 = classifier2.predict(X_test)

print(confusion_matrix(Y_test, Y_pred2))
print(accuracy_score(Y_test, Y_pred2)*100)

[[ 23   7   9  39  72]
 [  7   8   8  65  90]
 [  3   3   9 121 148]
 [ 11   5  15 276 389]
 [  8   2  12 222 448]]
38.2


In [13]:
from sklearn.svm import SVC
classifier3 = SVC(kernel = 'rbf')
classifier3.fit(X_train, Y_train)

Y_pred3 = classifier3.predict(X_test)

print(confusion_matrix(Y_test, Y_pred3))
print(accuracy_score(Y_test, Y_pred3)*100)

[[ 36  13   7  63  31]
 [ 14  19  20 107  18]
 [  1   6  30 201  46]
 [  3   1  13 458 221]
 [  1   0   4 241 446]]
49.45


In [17]:
from sklearn.naive_bayes import MultinomialNB
classifier4 = MultinomialNB()
classifier4.fit(X_train, Y_train)

Y_pred4 = classifier4.predict(X_test)

print(confusion_matrix(Y_test, Y_pred4))
print(accuracy_score(Y_test, Y_pred4)*100)


[[ 61  29  20  27  13]
 [ 12  24  44  80  18]
 [  6  10  48 186  34]
 [  3   6  29 486 172]
 [  7   2  10 297 376]]
49.75


In [19]:
print(classification_report(Y_test, Y_pred4))

              precision    recall  f1-score   support

           1       0.69      0.41      0.51       150
           2       0.34      0.13      0.19       178
           3       0.32      0.17      0.22       284
           4       0.45      0.70      0.55       696
           5       0.61      0.54      0.58       692

    accuracy                           0.50      2000
   macro avg       0.48      0.39      0.41      2000
weighted avg       0.50      0.50      0.48      2000



In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier5 = DecisionTreeClassifier(criterion = 'entropy')
classifier5.fit(X_train, Y_train)

Y_pred5 = classifier5.predict(X_test)

print(confusion_matrix(Y_test, Y_pred4))
print(accuracy_score(Y_test, Y_pred4)*100)

[[ 39  23  16  38  34]
 [ 34  28  27  47  42]
 [ 57  38  54  62  73]
 [110  82 126 158 220]
 [115  87 109 150 231]]
25.5


In [16]:
from sklearn.ensemble import RandomForestClassifier
classifier6 = RandomForestClassifier(criterion = 'entropy', n_estimators = 100)
classifier6.fit(X_train, Y_train)

Y_pred6 = classifier6.predict(X_test)

print(confusion_matrix(Y_test, Y_pred6))
print(accuracy_score(Y_test, Y_pred6)*100)

[[ 31   9   8  56  46]
 [  6   5  11 118  38]
 [  4   1   4 216  59]
 [  5   0   8 468 215]
 [  6   0   0 278 408]]
45.800000000000004
